### ISSUE TITLE
Big files

### ISSUE THREAD

**Issue by CherryAnt** [TheSHEEEP/MTGDownloader#1]
Hi,
I am using you script for doing a new one, and i see downloading files is too slow, more than 1 min for 4MB
Do you know what can it be?

**Comment by TheSHEEEP** [comment]
Sorry, not really. Aside from obvious connection issues on your side, but you probably checked that already.

However, I did find the URLLoader EXTREMELY unreliable on linux (which is why I stopped working on this ultimately), so if you are on linux, be aware there are issues.
